import type { Metadata } from "next";
import "./globals.css";

import { Navbar } from "@/components/navbar";
import { ThemeProvider } from "next-themes";
import Footer from "@/components/footer";

import { GoogleAnalytics } from "@next/third-parties/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col h-screen w-screen overflow-x-hidden overflow-y-auto">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          <main className="flex flex-col flex-1 p-4">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
      <GoogleAnalytics gaId="G-W9DDJJTE4L" />
    </html>
  );
}
